# FILE: _config.yml
# Konfigurasi dasar Jekyll

title: My Photo Gallery
email: shortname@success@gmail.com
description: >-
  Galeri foto keren dengan sentuhan Cyberpunk Pixel Art.

# Konfigurasi Build
markdown: kramdown
theme: null # Pastikan ini ditulis 'null' (huruf kecil)
exclude:
  - README.md
