# FILE: netlify.toml (DI ROOT REPO)

[build]
  # Folder publish harus titik ('.') jika file Anda di root repo
  publish = "." 
  command = ""

# Redirect untuk memastikan admin/index.html selalu ter-serve (menggantikan _redirects)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

# Pengaturan Lingkungan untuk Identitas (Fix Reset Password)
[build.environment]
  # Ini mengatasi masalah tautan reset password
  GOTRUE_URL = "https://kanaawesome.netlify.app/.netlify/identity"
