# FILE: netlify.toml (DI ROOT REPO)

[build]
  publish = "."
  command = ""

# Redirect untuk memastikan admin/index.html selalu ter-serve
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

# Pengaturan Lingkungan untuk Identitas (Fix Reset Password)
[build.environment]
  # Ini mengatasi masalah tautan reset password
  GOTRUE_URL = "https://kanaawesome.netlify.app/.netlify/identity" 
  # Tambahkan ini: Arahkan ke halaman admin setelah email diklik
  URL = "https://kanaawesome.netlify.app/admin/"
