# FILE: admin/config.yml

backend:
  name: git-gateway   # Menggunakan Netlify Git Gateway untuk Auth
  branch: main        # Ganti jika branch utama Anda bukan 'main'

# Pengaturan Media
media_folder: "images"          # Folder di repo GitHub tempat file gambar diupload (Wajib ada!)
public_folder: "/images"        # Path publik untuk mengakses gambar di website

# Definisi Koleksi (Menu CMS)
collections:
  - name: "gallery"
    label: "Galeri Foto Pixel Art"
    folder: "_data" # Folder di repo tempat file data koleksi disimpan
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Galeri (Internal)", name: "gallery_title", widget: "string" }
      - label: "Foto-foto"
        name: "photos"
        widget: "list"
        fields:
          - { label: "Foto (Upload)", name: "image", widget: "image" }
          - { label: "Caption Foto", name: "caption", widget: "string" }
