backend:
  name: github
  repo: Senboy-Tech/My-Awesome-Site
  branch: main

media_folder: "images"       # folder di repo tempat file disimpan
public_folder: "/images"     # path public di website

collections:
  - name: "gallery"
    label: "Galeri Foto Pixel Art"
    folder: "_data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama Galeri (Internal)", name: "title", widget: "string" }
      - label: "Foto-foto"
        name: "photos"
        widget: "list"
        fields:
          - { label: "Foto (Upload)", name: "image", widget: "image" }
          - { label: "Caption Foto", name: "caption", widget: "string" }
