# FILE: admin/config.yml

backend:
  name: git-gateway   # HARUS MENGGUNAKAN INI UNTUK NETLIFY DEPLOY
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "Galeri Foto Pixel Art"
    folder: "_data"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Nama Galeri (Internal)"
        name: "gallery_title"
        widget: "string"
      - label: "Foto-foto"
        name: "photos"
        widget: "list"
        fields:
          - label: "Foto (Upload)"
            name: "image"
            widget: "image"
          - label: "Caption Foto"
            name: "caption"
            widget: "string"
